require("augusto.options")
require("augusto.autocommands")
require("augusto.keymaps")
require("augusto.lazy")
require("augusto.plugin.tokyonight")
require("augusto.plugin.treesitter")
require("augusto.plugin.lspconfig")
require("augusto.plugin.lualine")
require("augusto.plugin.nvimtree")
require("augusto.plugin.telescope")
require("augusto.plugin.toggleterm")

